name = "SignedDistanceFunctions"
uuid = "5d155b53-3349-4453-ad1f-ebdf13404c93"
authors = ["Tom Gillam <tpgillam@googlemail.com>"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
